name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run Python script
        env:
          VENDOR_USERNAME: ${{ secrets.VENDOR_USERNAME }}
          VENDOR_PASSWORD: ${{ secrets.VENDOR_PASSWORD }}
        run: python app.py
